"""
Django settings for quevesve_back project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import sys
from datetime import timedelta
from pathlib import Path

from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'storages',
    'axes',
]

LOCAL_APPS = [
    'users',
    'videos',
    'direct_messages',
    'reports',
]

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INSTALLED_APPS = THIRD_PARTY_APPS + LOCAL_APPS + DJANGO_APPS

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'quevesve_back.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '300/min',
        'login': '5/min',
        'register': '3/min',
        'social_auth': '10/min',
        'video_upload': '6/hour',
    },
    # nginx es el único proxy confiable delante de Django (Cloudflare -> nginx -> Django),
    # así DRF toma el hop correcto de X-Forwarded-For para el rate limiting por IP en vez
    # de confiar en un valor que un cliente podría intentar falsificar.
    'NUM_PROXIES': 1,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}


AUTH_USER_MODEL = 'users.CustomUser'

# django-axes: lockout de cuentas tras intentos fallidos de login, capa adicional al
# rate limiting (que solo limita ráfagas por minuto). Axes acumula fallos a lo largo de
# AXES_COOLOFF_TIME entero, así que frena también a un atacante que reintenta lento para
# esquivar el throttle por minuto.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Bloquea si CUALQUIERA de los dos contadores llega al límite: por username (protege una
# cuenta puntual de credential stuffing aunque el atacante rote de IP) o por IP (protege
# contra un atacante probando muchos usuarios distintos desde el mismo origen). El costo de
# esta elección: alguien que sepa un username válido podría, a propósito, bloquear esa
# cuenta por una hora fallando el login adrede — trade-off aceptado, es el mismo que usan
# la mayoría de apps con este tipo de protección.
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(hours=1)
AXES_RESET_ON_SUCCESS = True
# Evita que reintentos durante el lockout extiendan el cooloff indefinidamente.
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = False
# Sin esto, axes.middleware.AxesMiddleware reemplaza la respuesta con su página HTML de
# bloqueo por default, sin importar lo que devuelva la vista de login.
AXES_LOCKOUT_CALLABLE = 'quevesve_back.axes_handlers.axes_lockout_response'

# Cache compartido (contadores de rate limiting de DRF). Sin Redis, el cache por defecto
# es LocMemCache por proceso, que NO se comparte entre workers de Gunicorn ni entre
# réplicas del contenedor `web` — el throttling sería inconsistente en producción.
REDIS_URL = config('REDIS_URL', default='')

if 'test' in sys.argv or 'test_coverage' in sys.argv:
    # Nunca requerir un Redis corriendo para la suite de tests / CI.
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
elif REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'},
            'KEY_PREFIX': 'quevesve',
        }
    }
else:
    # Fallback de conveniencia para dev (un solo proceso `runserver`): los contadores de
    # throttling no se comparten entre procesos, así que producción DEBE setear REDIS_URL.
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Debe ir al final: procesa la respuesta cuando axes.backends.AxesBackend
    # bloqueó un intento de login por lockout.
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'quevesve_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quevesve_back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if 'test' in sys.argv or os.getenv('GITHUB_ACTIONS'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('TEST_DATABASE_NAME', default='test_db_name'),
            'USER': config('TEST_DATABASE_USER', default='test_db_user'),
            'PASSWORD': config('TEST_DATABASE_PASSWORD', default='test_db_password'),
            'HOST': config('TEST_DATABASE_HOST', default='localhost'),
            'PORT': config('TEST_DATABASE_PORT', cast=int, default=5432),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DATABASE_NAME'),
            'USER': config('DATABASE_USER'),
            'PASSWORD': config('DATABASE_PASSWORD'),
            'HOST': config('DATABASE_HOST'),
            'PORT': config('DATABASE_PORT', cast=int),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'users.validators.StrongPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Storage de media (video/thumbnails/fotos de perfil) — Cloudflare R2 en producción para
# evitar cargos de egress de DigitalOcean; filesystem local en dev/tests. MEDIA_ROOT sigue
# usándose como origen para el comando de migración `migrate_media_to_r2` y en dev/tests.
USE_R2_STORAGE = config('USE_R2_STORAGE', default=False, cast=bool) and not (
    'test' in sys.argv or 'test_coverage' in sys.argv
)

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
}

if USE_R2_STORAGE:
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'access_key': config('R2_ACCESS_KEY_ID'),
            'secret_key': config('R2_SECRET_ACCESS_KEY'),
            'bucket_name': config('R2_BUCKET_NAME'),
            'endpoint_url': config('R2_ENDPOINT_URL'),
            'region_name': 'auto',
            'signature_version': 's3v4',
            'addressing_style': 'virtual',
            'custom_domain': config('R2_PUBLIC_DOMAIN'),
            'querystring_auth': False,
            'file_overwrite': False,
            'default_acl': None,
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if not DEBUG:
    # HTTPS is terminated by Cloudflare + nginx; Django must NOT redirect internally
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Email — en dev imprime en consola; en prod usa Gmail SMTP
_default_email_backend = (
    'django.core.mail.backends.console.EmailBackend'
    if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_BACKEND = config('EMAIL_BACKEND', default=_default_email_backend)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = f"QueVesVe!& <{config('EMAIL_HOST_USER', default='no-reply@quevesve.app')}>"
BACKEND_BASE_URL = config('BACKEND_BASE_URL', default='http://localhost:8000')

# CORS — permite que el frontend (Expo web/móvil) acceda a la API
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:8081,http://localhost:19006',
).split(',')
CORS_ALLOW_CREDENTIALS = False

# Social auth — Client IDs propios contra los que se valida el `audience` de los
# tokens de Google/Facebook, para evitar aceptar tokens emitidos para otra app.
GOOGLE_OAUTH_CLIENT_IDS = [
    c.strip() for c in config('GOOGLE_OAUTH_CLIENT_IDS', default='').split(',') if c.strip()
]
FACEBOOK_APP_ID = config('FACEBOOK_APP_ID', default='')

# Límites y compresión de video subido por usuarios (UGC)
MAX_UGC_VIDEO_DURATION_SECONDS = config('MAX_UGC_VIDEO_DURATION_SECONDS', default=60, cast=int)
UGC_STORAGE_QUOTA_BYTES = config('UGC_STORAGE_QUOTA_BYTES', default=500 * 1024 * 1024, cast=int)
UGC_COMPRESS_MAX_HEIGHT = config('UGC_COMPRESS_MAX_HEIGHT', default=720, cast=int)
UGC_COMPRESS_VIDEO_BITRATE = config('UGC_COMPRESS_VIDEO_BITRATE', default='2500k')
UGC_COMPRESS_AUDIO_BITRATE = config('UGC_COMPRESS_AUDIO_BITRATE', default='128k')

# Presupuesto de almacenamiento del catálogo propio (Pexels/Pixabay/Archive), usado por
# el comando cleanup_storage para decidir cuándo purgar el contenido más viejo.
CATALOG_STORAGE_BUDGET_BYTES = config(
    'CATALOG_STORAGE_BUDGET_BYTES', default=5 * 1024 * 1024 * 1024, cast=int,
)

# Notificaciones de errores 500 por email cuando DEBUG=False
ADMINS = [('QueVesVe Admin', EMAIL_HOST_USER)] if not DEBUG and EMAIL_HOST_USER else []
SERVER_EMAIL = EMAIL_HOST_USER or 'root@localhost'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {'format': '%(asctime)s - %(levelname)s - %(name)s - %(message)s'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'default'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if not DEBUG else 'DEBUG',
    },
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'INFO' if not DEBUG else 'DEBUG', 'propagate': False},
    },
}

# Tests
if 'test' in sys.argv or 'test_coverage' in sys.argv:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'test_media')

    # El cache (LocMemCache, ver arriba) persiste durante toda la corrida de tests, y ahí
    # es donde DRF guarda los contadores de rate limiting. Sin limpiarlo entre tests, los
    # contadores se acumulan entre métodos/clases y pueden producir 429 en tests que no
    # tienen nada que ver con throttling. Se limpia antes de cada test individual.
    # `_pre_setup` es un classmethod en Django >=6 y un método de instancia en versiones
    # previas — se detecta la forma real para no romper el binding en ningún caso.
    from django.test.testcases import SimpleTestCase
    from django.core.cache import cache as _cache

    _original_pre_setup = SimpleTestCase.__dict__['_pre_setup']

    if isinstance(_original_pre_setup, classmethod):
        _original_pre_setup_func = _original_pre_setup.__func__

        @classmethod
        def _pre_setup_and_clear_cache(cls, *args, **kwargs):
            _cache.clear()
            return _original_pre_setup_func(cls, *args, **kwargs)
    else:
        def _pre_setup_and_clear_cache(self, *args, **kwargs):
            _cache.clear()
            return _original_pre_setup(self, *args, **kwargs)

    SimpleTestCase._pre_setup = _pre_setup_and_clear_cache
