name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: test_db_name
          POSTGRES_USER: test_db_user
          POSTGRES_PASSWORD: test_db_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev --skip-lock

    - name: Run migrations
      run: |
        pipenv run python manage.py migrate --noinput
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    - name: Run tests
      run: |
        pipenv run python manage.py test
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    - name: Install PostgreSQL client
      run: |
        sudo apt-get install postgresql-client

    - name: Check PostgreSQL service
      run: |
        pg_isready -h localhost -p 5432 -U test_db_user

    - name: Run tests with coverage
      run: |
        pipenv run coverage run --source='.' manage.py test
        pipenv run coverage xml -o coverage.xml
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
